# Main CI file
# https://docs.gitlab.com/ee/ci/yaml/#gitlab-ci-yml

stages:
  - install
  - test
  - docs
  - deploy


cache:
  paths:
    - .pip37
    - .pip36

# test install on python 3.6
install-on-python-3.6:
  stage: install
  image: bilbydev/bilby_pipe-test-suite-python36
  script:
    - conda install -c conda-forge schwimmbad
    - mkdir -p .pip36
    - pip install --upgrade pip
    - pip --cache-dir=.pip36 install --upgrade bilby
    - pip --cache-dir=.pip36 install .

# test install on python 3.7
install-on-python-3.7:
  stage: install
  image: bilbydev/bilby_pipe-test-suite-python37
  script:
    - conda install -c conda-forge schwimmbad
    - mkdir -p .pip37
    - pip install --upgrade pip
    - pip --cache-dir=.pip37 install --upgrade bilby
    - pip --cache-dir=.pip37 install .


# Include the additional CI tasks
include:
    - local: "/ci_workflows/tests.yml"
    - local: "/ci_workflows/make_docs.yml"
    - local: "/ci_workflows/pypi_deploy.yml"
    - local: "/ci_workflows/end_to_end_analysis.yml"
