# Main CI file
# https://docs.gitlab.com/ee/ci/yaml/#gitlab-ci-yml

stages:
  - test
  - docs
  - deploy


cache:
  paths:
    - .pip37
    - .pip36

## All  CI workflows in the following folder
include:
  - local: './ci_workflows/*.yml'
